name: "Clover test coverage check"
description: "Verify that your test coverage meets the requirements."
author: "Johan van Helden <johan@johanvanhelden.com>"
branding:
  icon: "check"
  color: "green"
inputs:
  filename:
    description: "The filename of the clover coverage XML file."
    required: true
    default: "coverage.xml"
  percentage:
    description: "The minimum percentage of coverage allowed."
    required: true
    default: "95"
  precision:
    description: "The precision of the coverage value."
    required: false
    default: ""
  precision-display:
    description: "The precision of the coverage display value."
    required: false
    default: ""
  exit:
    description: "If the coverage check should exit."
    required: false
    default: ""
outputs:
  coverage:
    description: "The processed value from the XML file."
runs:
  using: "docker"
  #image: "docker://johanvanhelden/gha-clover-test-coverage-check:v1"
  image: "Dockerfile"
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.percentage }}
    - ${{ inputs.precision }}
    - ${{ inputs.precision-display }}
    - ${{ inputs.exit }}
