version: "3"

services:
  clover-coverage-check:
    container_name: clover-coverage-check
    build: .
    volumes:
      - ./tests:/tests
    #
    # test a failed coverage check:
    command: ["/tests/Fixtures/coverage_1.xml", "3", "4", "", "false"]
    #
    # test a succesfull coverage check:
    #command: ["/tests/Fixtures/coverage_100.xml", "50", "4", "true"]
