version: "3"

services:
  clover-coverage-check:
    container_name: clover-coverage-check
    build: .
    volumes:
      - ./tests:/tests
    command: ["/tests/Fixtures/coverage_100.xml", "50", "2", "true"]
